### ISSUE TITLE
[4장] MySQL 표준 문법으로 작성된 쿼리의 타 DBMS 호환성

### ISSUE THREAD

**Issue by haedoang** [Growing-Up-Together/ReadingRecord#12]
> p.78 4.1.1.1 MySQL은 표준 SQL(ANSI SQL)문법을 지원하기 때문에 표준 문법에 따라 작성된 쿼리는 타 DBMS와 호환되어 실행될 수 있다 

위 부분의 내용이 이해가 잘 되지 않습니다 🤔

**Comment by heejin-ha** [comment]
MySQL은 ANSI SQL 문법을 지원하고, 
**MySQL 에서 작성한 ANSI SQL문은 타 DBMS와 호환되어 실행 가능하다** 로 이해하면 좋을 것 같습니다.

[ANSI SQL](https://velog.io/@gillog/ANSI-SQL%EC%9D%B4%EB%9E%80) 링크에서 오라클과 ANSI 문법 예제 확인하시면 도움될 것 같습니다.

@kchaw1 답변해주신 내용과 동일한 관점에서 답변 드립니다.
혹시 질문하시는 의도와 다른 답변이라면 코멘트 남겨주세요!

**Comment by haedoang** [comment]
감사합니다 이해되었습니다 🙇 🙇
