### ISSUE TITLE
[4장] 4.1.9 스레드풀

### ISSUE THREAD

**Issue by kchaw1** [Growing-Up-Together/ReadingRecord#13]
p95 그림 4.8 , 4.9가 잘 이해 되지 않습니다. 

그림 내의 COMMIT, QUERY, BEGIN 의 의미도요 !

**Comment by pageprologue** [comment]
Percona Server에서 선순위 큐에 대한 설정은 아래의 변수와 관련이 있습니다. 

- [thread_pool_high_prio_mode](https://docs.percona.com/percona-server/5.7/performance/threadpool.html#thread-pool-high-prio-mode)
  - 이 모드에는 `transactions`, `statements`, `none` 의 세부 항목이 있습니다.
  - `transactions`으로 설정하면 이미 시작된 트랜잭션의 명령문이 현재 연결에서 높은 우선순위를 가집니다.
  - `statements`으로 설정하면 모든 개별 명령문이 우선순위를 갖게 됩니다. 이 값을 전역(global)으로 설정하면 `none` 모드와 같습니다.
  - `none`은 연결에 대해 선순위 큐를 비활성화합니다.


그림 4.7과 4.8에서 COMMIT, QUERY, BEGIN의 순서에서 저도 의문이 들긴 했습니다. 
화살표가 반대로 된건가? 아니면 요청이 쌓인 순서를 보여주는 것인가?

보통 `BIGIN`은 `START TRANSACTION `과 같이 새로운 트랜잭션을 시작하는 것을 의미하고,
`COMMIT`은 현재 트랜잭션을 커밋하여 변경 사항을 영구적으로 저장하는 것을 의미합니다.
`QUERY`의 경우 SQL을 처리하는 동작이라고 이해할 수 있을 것 같습니다.

> p.94
> 먼저 실행된 트랜잭션 내에 속한 SQL을 빨리 처리해주면 해당 트랜잭션이 가지고 있던 잠금이  빨리 해제되고 잠금 경합을 낮춰서 전체적인 쿼리 성능을 향상시킬 수 있다.

여기서 말하는 내용은 `transactions`으로 설정한 예로 보입니다. (그림 4.8)

4.8 그림을 반대로 보면, `BEGIN`으로 트랜잭션이 시작된 요청대로 처리되는 것을 알 수 있습니다.

**Comment by heejin-ha** [comment]
[Percona Server 스레드 풀 - 트랜잭션 처리 관련](https://www.percona.com/blog/2014/01/29/percona-server-thread-pool-improvements/) 

> 참고) 아래 그림에서 화살표 방향이 헷갈리신다면
> Queuing Order 는 우측의 BEGIN이 1번째 요청이고, 좌측의 요청들이 순서대로 쌓인다고 생각하시면 됩니다
> Executing Order 는 좌측의 BEGIN이 1번째 실행 순서이고, 우층의 요청들이 순서대로 실행된다고 생각하시면 됩니다

![image](https://user-images.githubusercontent.com/85116037/183675649-659d1645-ba3b-4406-b621-b736c832ff7f.png)

파랑/초록/노랑 BEGIN, QUERY, COMMIT 순서대로 사용자 요청이 유입됩니다. -> Queuing Order
우선 순위를 적용하지 않은 상태에서 사용자 요청이 유입된 순서대로 요청을 처리합니다. -> Execution Order
파랑/초록/노랑 BEGIN, QUERY, COMMIT 순서대로 작업이 진행되며 마지막 파랑/초록/노랑 COMMIT 요청이 실행되는 시점에 각 트랜잭션의 쿼리가 처리되고 스레드 작업이 종료됩니다.

![image](https://user-images.githubusercontent.com/85116037/183676016-86398857-466f-4040-bbca-d6a3c85b5bdd.png)
파랑/초록/노랑 BEGIN, QUERY, COMMIT 순서대로 사용자 요청이 유입됩니다. -> Queuing Order
우선 순위가 적용되어 실행 순서가 재배치 되어 사용자 요청을 처리합니다. -> Execution Order
BEGIN 요청 이후 파랑 QUERY/COMMIT, 초록 QUERY/COMMIT, 노랑 QUERY/COMMIT 순으로  요청이 실행되어 COMMIT 요청 시점에 각 트랜잭션의 쿼리가 처리되고 스레드 작업이 종료됩니다.

-> 따라서 우선순위를 적용하여 실행순서가 재배치된 경우,
우선순위가 적용되지 않은 작업보다 트랜잭션 처리 시점이 빨라져 잠금 경합을 낮출 수 있으므로 전체적인 처리 성능이 향상됩니다.

BEGIN, QUERY, COMMIT 에 대한 정보는 @pageprologue 답변해주신 내용 참고 부탁드립니다.

**Comment by haedoang** [comment]
와.. 저도 찾고있었는데 @pageprologue  @heejin-ha 감사합니다 🙇🙇🙇 
책의 순서가 헷갈리게되어있는데 queue 구조로 이해하면 `BEGIN`이 앞쪽이라고 이해하시면 좋을것 같습니다
