### ISSUE TITLE
[6장] 버퍼 풀에서 압축 상태를 2가지로 관리하는 이유

### ISSUE THREAD

**Issue by pageprologue** [Growing-Up-Together/ReadingRecord#19]
> p.p192

InnoDB 버퍼 풀에서 압축된 상태(LRU 리스트)와 압축이 해제된 상태(Unzip_LRU 리스트)로 2개의 버전을 관리하는 이유가 뭘까요?

**Comment by haedoang** [comment]
생각보다 오래 걸렸네요 😅 

LRU 리스트와 Unzip_LRU 리스트를 구분하는 것은 `테이블의 압축 여부`입니다 

압축된 테이블의 압축 해제된 데이터 페이지는 Unzip_LRU 리스트에서 관리됩니다.

`p.192` 쪽에서 나와있던 내용에 압축된 테이블의 데이터 페이지를 InnoDB 스토리지 엔진에서는 버퍼풀에 `압축된 상태` 와 `압축이 해제된 상태` 로 관리한다고 나와있습니다. 

압축된 페이지는 압축된 페이지로 메모리에 로드되며, 즉시 압축이 풀리지 않고 필요할 때 압축을 해제하기 때문에 압축된 상태와 압축이 해제된 상태,  두 가지 형태로 관리됩니다.

압축된 데이터 페이지는 바로 `CRUD`  명령으로 사용할 수 없고 압축이 해제가 되어야 사용이 가능합니다.

압축이 해제된 데이터 페이지는 Unzip_LRU 리스트에서 관리를 하게 됩니다.  

처음으로 stackoverflow 질문을 남겨보았네요 😄 

참고 자료 하단에 첨부합니다. 

혹시나 잘못 전달한 내용이 있으면 말씀해주세요 

[https://stackoverflow.com/questions/73576645/what-is-unzip-lru-list](https://stackoverflow.com/questions/73576645/what-is-unzip-lru-list)
[https://javamana.com/2022/01/202201022305337603.html](https://javamana.com/2022/01/202201022305337603.html)
[https://zhuanlan.zhihu.com/p/146168601](https://zhuanlan.zhihu.com/p/146168601)

**Comment by pageprologue** [comment]
압축된 테이블을 버퍼 풀에서 관리할 때는, CRUD 명령이 실행되기 전까지는 LRU 리스트에서 관리하고 CRUD 명령이 수행되면 압축이 해제되어 Unzip_LRU 리스트에서 관리하게 된다고 이해했습니다. 

stackoverflow에 질문도 남겨주셨군요! 감사합니다👍
