### ISSUE TITLE
[7장] AES 암호화 알고리즘은 암호화되지 않은 테이블과 동일한 크기의 데이터 파일을 가진다

### ISSUE THREAD

**Issue by haedoang** [Growing-Up-Together/ReadingRecord#20]
> p.199 9번째 라인. AES 암호화 알고리즘은 암호화하고자 하는 평문의 길이가 짧은 경우 암호화 키의 크기에 따라 암호화된 결과의 용량이 더 커질 수도 있지만, 이미 데이터 페이지는 암호화 키보다 훨씬 크기 때문에 암호화 결과가 평문의 결과와 동일한 크기의 암호문을 반환한다 

위의 문장을 어떻게 해석해야 하는 지 잘 모르겠습니다 🤔 
암호화 키에 의해서 평문이 암호화될 때 평문보다 용량이 커질 수가 있는데, 암호화 결과가 평문의 결과와 동일한 크기의 암호문을 반환한다는 것인지 이 문장이 잘 이해가 되지 않습니다

**Comment by pageprologue** [comment]
질문으로 남겨주신 문장을 개인적으로 이해한 대로 정리해 보았습니다.
- AES 암호화 알고리즘은 평문의 데이터가 작은 경우에는 암호화된 데이터 크기가 평문보다 더 커질 수 있다.
- AES 암호화 알고리즘은 평문의 데이터가 충분히 크다면 파일의 크기는 암호화 전과 후가 크게 다르지 않다.

AES 암호화 알고리즘에 대해 저도 잘 몰랐는데 아래와 같은 특징이 있다고 합니다.
- AES(Advanced Encryption Standard) 키는 세 가지 길이(128, 192 또는 256비트)의 대칭 키이다.
- AES는 기본적으로는 블록암호화함수라 입력값과 출력값의 길이가 동일하다. 다만, 패딩이 붙기 때문에 실제 길이보다 살짝 늘어나게 된다. 

AES 암호화 알고리즘에 대한 자세한 내용은 모르겠지만, 평문 데이터가 충분히 크면 평문과 암호문의 길이가 비슷한 것 같습니다!

참고 사이트
- [AES-256 암호화 후의 길이는 얼마일까](https://blog.huiya.me/13)
- [블록 암호 알고리즘](http://www.ktword.co.kr/test/view/view.php?m_temp1=3037)

**Comment by haedoang** [comment]
감사합니다 위니님 👍
