### ISSUE TITLE
[8장] 8.3.7 B-Tree 인덱스 효율성 설명 관련 질문

### ISSUE THREAD

**Issue by haedoang** [Growing-Up-Together/ReadingRecord#24]
> p.248 5번째 줄에 케이스 B 인덱스는 우선 "emp_no >= 10144 AND dept_no='d002'"인 레코드를 찾고..

이 부분이 `emp>no >= 10444` 인 레코드 7건을 먼저 찾고, 이후에 두번째 컬럼인 `dept_no='d002'`로 비교를 해서 5건으로 필터링 작업을 하는 것으로 

생각했는데 다른 분들은 어떻게 생각하시는지 궁금합니다 🤔

as-is : `emp_no >= 10144 AND dept_no='d002'`
to-be : `emp_no >= 10444`

**Comment by heejin-ha** [comment]
저는 `emp_no >= 10444 and dept_no='d002'` 두 조건을 만족하는 레코드를 찾는다고 생각했습니다.
두 조건 만족하는 레코드를 찾은 이후로는 emp_no가 정렬되어 있으니 이후 데이터를 읽으면서 `dept_no='d002'` 조건에 만족하는 데이터를 찾는 방식으로 이해했습니닷..🤔

**Comment by pageprologue** [comment]
제 생각에도 부등호 조건 사용 시 인덱스가 생성된 순서를 고려해서 조건을 거는 것이 효율적이라는 의미로 이해했습니다.

- 케이스 A: INDEX(dept_no, emp_no)
- 케이스 B: INDEX(emp_no, dept_no)

A 인덱스의 경우 dept_no로 먼저 정렬되고, 그 다음에 emp_no로 정렬되어 있기 때문에 dept_no가 'd002'인 항목에서 emp_no가 '10444' 보다 크거나 같은 항목을 찾으면 dept_no가 바뀌기 전까지 쭉 읽으면 됩니다.
B 인덱스이 경우에는 emp_no로 정렬되어 있어서 emp_no가 '10444' 보다 크거나 같은 항목을 찾은 뒤, 각각의 항목에 대해 dept_no가 'd002'인 레코드를 검색하게 되어 비효율적이게 되는 것 같습니다.

**Comment by haedoang** [comment]
히동님 말씀대로면 두 조건을 만족하는 row는 dept_no='d002' 조건을 만족할텐데 dept_no 조건을 다시 한다는 것일까요??

**Comment by haedoang** [comment]
✅ 인덱스의 첫번째를 기준으로 정렬되므로 두가지 조건을 먼저 만족하는 row 를 찾은 후 이후의 row들을 두가지 조건으로 모두 조회해야 한다
