### ISSUE TITLE
[8장] R-Tree 인덱스 예제 ST_Distance_Sphere() 사용 관련 질문

### ISSUE THREAD

**Issue by haedoang** [Growing-Up-Together/ReadingRecord#25]
> p.257 R-Tree 인덱스 좌표 검색 예제 관련

R-Tree 인덱스로 특정 지점을 기준으로 위치를 검색하는 예제를 작성하는 이슈가 발생하여 문의드립니다

```SQL
create table tb_location (
    id BIGINT NOT NULL AUTO_INCREMENT,
    geo GEOMETRY NOT NULL,
    PRIMARY KEY (id),
    SPATIAL KEY sx_geo (geo)
) ENGINE=INNODB;


-- p
insert into tb_location (geo)
  values (point(5,5));

-- p1
insert into tb_location (geo)
  values (point(6,11));

-- p2
insert into tb_location (geo)
  values (point(9,4));

-- p3
insert into tb_location (geo)
  values (point(-2,1));

-- p4
insert into tb_location (geo)
  values (point(3,1));

-- p5
insert into tb_location (geo)
  values (point(11,11));

-- p6
insert into tb_location (geo)
  values (point(1,9));

-- p7
insert into tb_location (geo)
  values (point(11,1));

SELECT id, ST_AsText(geo), ST_DISTANCE_SPHERE(POINT(5, 5), geo) AS dist
  from tb_location;
```

위의 데이터로 예제를 만들고 있는데 책에서는 distance가 `km` 이기 때문에 거리에 1000을 곱하였는데 
제대로 된 결과가 출력되지 않아 확인해보니 거리가 다르게 표시되었습니다. 

id, point, dist
1,POINT(5 5),0
2,POINT(3 1),497121.1812731935
3,POINT(6 11),676185.1019481792
4,POINT(9 4),457131.2756690849
5,POINT(-2 1),895414.8289373002
6,POINT(11 11),938709.0203203298
7,POINT(1 9),626605.2492226522
8,POINT(11 1),800961.4581396672

거리에 `100000` 을 곱하니까 정상적으로 출력되었습니다 

혹시 관련 이슈 겪으신 분 있을까요 ? 🤔

**Comment by haedoang** [comment]
✅ 예제의 좌표값이 실제 경도, 위도를 나타내는 것이 아니라 단순 숫자로 표현했기 때문에 오해의 소지가 있음
✅ 거리 5의 차이는 실제 5Km가 아님

**Comment by kchaw1** [comment]
책의 그림[8.24] (p257) 와 같이 단순한 평면상 좌표가 아니라 현실세계의 위도 경도 기준이라 예제의 거리가 오해의소지가 있는듯합니다 !
