### ISSUE TITLE
[8장] 작업 범위 결정 조건으로 인덱스를 사용하는 경우

### ISSUE THREAD

**Issue by pageprologue** [Growing-Up-Together/ReadingRecord#26]
> p.252
> 위의 두 가지 조건을 만족하는 쿼리는 column_1 부터 column_i 까지는 작업 범위 결정 조건으로 사용되고, column_(i+1) 부터 column_n 까지의 조건은 체크 조건으로 사용된다.

위의 문장이 잘 이해가 가지 않습니다.
n 값이 5이고, i 값이 3일 때, `... WHERE column_1 = 1 AND column_2 = 2 AND column_3 = 3` 이와 같은 조건에서는 column_1, column_2, column_3 이 모두 작업 범위 조건으로 사용될 수 있는데요.
여기서 column_4 부터 column_5 까지의 조건은 체크 조건으로 사용된다고 하는게 무슨 의미일까요?
그냥 작업 범위 결정 조건을 만족하지 않으면 인덱스가 사용되지 않는다고 이해하긴 했는데, 뒷 문장에서 `i+1`, `n`이 이해가 잘 안갑니다.

**Comment by haedoang** [comment]
✅ 범위 결정 조건에 사용되지 않은 인덱스는 모두 체크 조건이 된다
