### ISSUE TITLE
[9장] Block Nested Loop 조인 실행 계획 관련 질문

### ISSUE THREAD

**Issue by haedoang** [Growing-Up-Together/ReadingRecord#28]
> p.322-323 조인 버퍼를 사용하는 조인 예제 관련

323쪽 아래에서 4번째줄에서 실제 드라이빙 테이블 결과를 조인 버퍼에 담아두고, 드리븐 테이블을 먼저 읽고 조인 버퍼에서 일치하는 레코드를 찾는 방식으로 정렬된다고 나와있는데요 

322쪽에서 실행계획 결과는`dept_emp_de` 테이블이 드라이빙 테이블,
`employees` 가 드리븐으로 표시되어 있고, block nested loop 조인이고 명시되어 있습니다.

그렇다면 결과적으로 `block nested loop` 조인 방식을 사용하는 경우에는 
실행계획에서 드리븐 테이블로 사용된 테이블의 인덱스를 기준으로 정렬이 된다고 생각해도 되는걸까요 ? 🤔🤔 

교재에서는 정렬 순서가 흐트러질 수 있다고 나와 있어서 헷갈리네요 😅

**Comment by heejin-ha** [comment]
조인이 처리될 때 조인 버퍼를 사용하느냐 차이인 것 같습니다.

일반 조인인 경우, 드라이빙 테이블의 순서로 조인 결과를 가져옵니다
조인 버퍼를 사용한 조인인 경우, 드라이빙 테이블을 조인 버퍼에 담아둔 후 드리븐 테이블을 먼저 읽기 때문에 드리븐 테이블 기준으로 조인이 실행됩니다.

이렇게 조인 버퍼 사용 유무에 따라 정렬 순서가 흐트러질 수 있다는 의미인것 같습니다

**Comment by haedoang** [comment]
감사합니다 !!

block nested loop 조인 시 정렬이 흐트러질 수 있다고 생각했었네요! 
 -> block nested loop 조인 시 => 조인 버퍼 사용 유무

그리고 block nested loop  사용 시 실행계획에서 드라이빙 테이블의 인덱스로 정렬되지 않고 변경될 수 있다는 것(현재 사용되지 않는 이유인것 같네요🤔)과 헷갈렸었는데 설명해주신 것으로 이해가 되었습니다 👍👍👍
