### ISSUE TITLE
[10장] 인덱스 및 테이블의 통계 정보

### ISSUE THREAD

**Issue by pageprologue** [Growing-Up-Together/ReadingRecord#30]
> p.397

통계 정보의 각 컬럼 값에 대한 설명이 나와 있는데요. 
해당 건수를 어떻게 계산하는 것인지 잘 이해가 안됩니다.
특히, 테이블의 전체 레코드 건수가 300024건인데, 여기에는 299202건으로 나옵니다.
이 부분에 대해 설명해주실 수 있을까요?

**Comment by haedoang** [comment]
공식 문서를 찾아보았는데도 명확한 답을 찾지 못했네요 
[https://stackoverflow.com/questions/74162283/n-diff-pfxnn-does-not-match-index-unique-count-in-mysql8](https://stackoverflow.com/questions/74162283/n-diff-pfxnn-does-not-match-index-unique-count-in-mysql8) 
stackoverflow에 질문을 올려보았는데 답변이 아직 없네요 😭  
좀 더 확인 해보도록하겠습니다 🙇
