### ISSUE TITLE
[10장] 서브쿼리 vs 조인 성능 차이

### ISSUE THREAD

**Issue by haedoang** [Growing-Up-Together/ReadingRecord#32]
> p.426 서브쿼리는 조인보다 성능이 떨어진다

9장 옵티마이저에서  8.0버전부터 지원하는 다양한 세미조인 최적화 방식들을 학습했는데요

그럼에도 아직까지 서브쿼리가 조인보다 성능이 떨어지는 것인지 궁금하네요 🤔🤔

관련 내용을 찾아보다가 서브 쿼리와 조인에 대한 글을 찾았는데 

아래 내용은 8.0 버전에서 외부쿼리로 재작성하는 형태의 테이블 풀 아웃 최적화로 개선된 부분이 아닌가 한데 

어떻게 생각하시는지 질문드립니다 

[subquery vs join](https://stackoverflow.com/questions/141278/subqueries-vs-joins)  

1) 서브쿼리가 조인보다 성능이 떨어지는지 ? 
2) 상관 서브 쿼리는 드라이빙 테이블의 모든 ROW를 비교하는 방식이다(위의 링크 내용)은 테이블 풀-아웃 방식으로 최적화된 부분이 아닌지?

질문드립니다 🙇 🙇 🙇

**Comment by pageprologue** [comment]
### 1번 질문
버전에 따라 서브쿼리가 조인 보다 성능이 떨어질 수 있고, MySQL 8.0 이상의 버전이라도 옵티마이저가 서브쿼리를 최적화하는 실행 계획에 한계가 있을 수 있습니다.
- p. 335
    - MySQL 서버에서 세미 조인 최적화 기능이 없었을 때는, (...) 테이블을 풀 스캔하면서 한 건 한 건 서브쿼리의 조건에 일치하는지 비교했다.
    - (예제 쿼리 실행 계획에서) 대략 57건만 읽으면 될 쿼리를 30만 건 넘게 읽어서 처리된다.

- [jojoldu](https://jojoldu.tistory.com/520) 님의 블로그에서 결론만 정리한 내용입니다. 아래와 같은 이유로 서브쿼리를 지양하는 것이 좋을 것 같습니다.
    - MySQL 5.5 까지는 서브쿼리 최적화가 최악이라 웬만하면 Join으로 전환하자.
        - 메인테이블의 row 수 만큼 서브 쿼리를 수행한다.
    - MySQL 5.6 에서 서브 쿼리가 대폭 최적화 되었다.
        - 다만 최적화가 적용 안되는 조건들이 다수 존재한다.
    - 버전/조건 관계 없이 좋은 성능을 내려면 최대한 Join을 이용하자.
    - Join을 사용하기가 너무 어렵다면 Subquery는 사용하되, MySQL 5.5 이하라면 절대 사용하지 않는다.
        - 차라리 쿼리를 나눠서 2번 실행 (메인쿼리/서브쿼리)하고 애플리케이션에서 조립하는게 낫다.

### 2번 질문
질문에서 말씀해주신 것처럼 MySQL 8.0 버전에서는 테이블 풀-아웃 방식으로 개선 되었는데요.
다만, 최적화 되더라도 옵티마이저가 불필요한 서브쿼리는 조인으로 쿼리를 재작성 하는 것에 한계가 있다는 내용이 책에 나오고 있습니다.

- p.425
    - MySQL 5.5 버전까지는 파생 테이블에는 인덱스가 전혀 없으므로 다른 테이블과 조인할 때 성능상 불리할 때가 많았다.
    - MySQL 8.0 버전부터는 FROM 절의 서브쿼리에 대한 최적화도 많이 개선되어 가능하다면 불필요한 서브쿼리는 조인으로 쿼리를 재작성해서 처리한다. 하지만 옵티마이저가 처리할 수 있는 것은 한계가 있으므로 여전히 최적화된 쿼리를 작성하는 것은 중요하다.
