### ISSUE TITLE
[2장] mysqld_safe

### ISSUE THREAD

**Issue by pageprologue** [Growing-Up-Together/ReadingRecord#6]
> p.27
> systemd를 이용해 시작하고 종료할 수도 있지만, mysqld_safe 스크립트를 이용해서 시작하고 종료할 수도 있다.

`mysqld_safe`는 유닉스에서 `mysqld` 서버를 시작하는 데 권장되는 방법이라고 하는데, 어떤 방식으로 사용하는지 궁금합니다.

제가 찾아본 바로는 `mysqld_safe`는 에러가 발생했을 때 서버를 재구동 시키고 런타임 정보를 에러 로그에 기록하는 것과 같은 안전 기능을 추가로 가지고 있다고 합니다.

+ `--malloc-lib` 라이브러리도 찾아봤는데 어떤 라이브러인지, 왜 사용하는지 잘 모르겠습니다.
`--malloc-lib` : 동적 링크에 영향을 주는 LD_PRELOAD 환경 값을 수정하여 로더가 mysqld가 실행될 때 시스템 라이브러리 대신 메모리 할당 라이브러리를 찾을 수 있도록 한다.

- [mysqld_safe Docs](https://dev.mysql.com/doc/refman/8.0/en/mysqld-safe.html)

**Comment by haedoang** [comment]
docs를 참고해서 확인해보니 유닉스 기반 OS에서 mysql 서버를 시작하는데 권장하는 방법으로 확인하였습니다
`mysqld_safe` 으로 실행 시 설정 파일의 [myslqd_safe] 섹션 뿐 아니라 [mysqld] 섹션의 옵션도 읽는다고 하네요
안전 기능 지원 목적으로 사용되고 책에서 나온 예제에서는 `malloc` 라이브러리 옵션을 변경하는 기능을 소개하였는데요
Memory Allocator 라고하는 메모리 할당자의 변경 기능을 지원합니다 
정리한 내용 링크 공유합니다

[이슈6 정리](https://www.notion.so/mysqld_safe-66f05bdfb34f43b4b777a87ccac46e6c)

**Comment by pageprologue** [comment]
- mysqld_safe는 일종의 mysqld를 감시하는 데몬이라고 볼 수 있는데, 사용자가 mysqld_safe로 MySQL을 시작하면 mysqld_safe이 내부 스크립트에서 mysqld를 실행하고 mysqld 프로세스를 모니터링하고, 어떤 문제로 mysqld가 강제 종료하면 mysqld를 다시 시작하게 합니다. ( [출처](https://stricky.tistory.com/164))

- mysqld_safe를 사용하는 예로, [root 패스워드를 분실한 경우](https://zetawiki.com/wiki/MySQL_root_%ED%8C%A8%EC%8A%A4%EC%9B%8C%EB%93%9C_%EB%B6%84%EC%8B%A4)에 인증 생략 옵션 + 안전모드로 데몬 실행하도록 할 수 있습니다.
