### ISSUE TITLE
[3장] 사용자 권한 부여

### ISSUE THREAD

**Issue by pageprologue** [Growing-Up-Together/ReadingRecord#7]
> p.68

```sql
-- 글로벌 권한
GRANT SUPER ON *.* TO 'user'@'localhost';
-- DB 권한
GRANT EVENT ON *.* TO 'user'@'localhost';
```

위의 예제에서 처럼 사용자 권한을 부여하려고 하면 아래와 같은 오류가 발생합니다.

`Access denied for user 'user'@'localhost' (using password: YES)`

해결 방법을 같이 찾아보면 좋겠습니다.

**Comment by kchaw1** [comment]
안녕하세요 위니님. 저같은경우 위 상황이 재현이 안되네요 

환경이 다른가 싶어 도커에 가상 OS (ubuntu) 올리고 mysql 설치하여 테스트해봐도 정상동작하네요.

실행환경이 및 실행방법(순서)을 알려주시면 정리 끝나는대로 다시 살펴보겠습니다.

이미 관련자료 많이 찾아보셨겠지만 혹시 도움될까 싶어 링크 남겨드립니다.
https://changun516.tistory.com/55

**Comment by haedoang** [comment]
제 생각에는 위니님 DB에 'user'@'localhost' 가 등록이 안되어 있는 것 같아요🤔
```sql
  select user, host from mysql.user
```
에서 조회 되는지 확인필요할 것 같습니다

**Comment by pageprologue** [comment]
제가 `Access denied` 오류가 발생한 이유는 역할을 부여할 때 해당 계정에 `WITH GRANT OPTION`이 없어서 그랬던 것 같습니다.
> p.68
GRANT OPTION 권한은 다른 권한과 달리 명령의 마지막에 `WITH GRANT OPTION`을 명시해서 부여한다.

또한, 'user'@'localhost' 와 'user'@'%' 계정은 다른데, 생성되지 않은 계정에 역할을 부여하려고 하면 `You are not allowed to create a user with GRANT` 오류가 납니다.
