### ISSUE TITLE
[3장] Native Authentication 동적 변수 변경 오류(read only variables)

### ISSUE THREAD

**Issue by haedoang** [Growing-Up-Together/ReadingRecord#9]
> p.57 Native Authentication 글로벌 변수 변경 시 아래와 같은 오류가 발생하는데 왜그럴까요?🤔

```sql
SET GLOBAL default_authentication_plugin='mysql_native_password';
```
 `[HY000][1238] Variable 'default_authentication_plugin' is a read only variable`

**Comment by kchaw1** [comment]
저도 같은 에러가 나고 관련하여 자료를 찾아 보았습니다.

https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin

[원문 일부 발췌]
As of MySQL 8.0.27, which introduces multifactor authentication, [default_authentication_plugin] is still used, but in conjunction with and at a lower precedence than the [authentication_policy] system variable

공식문서상에 default_authentication_plugin 변수는
8.0.27 버전에 Deprecated 되었고 추후 없어질 예정이라고 합니다.

현재 default_authentication_plugin 변수는 authentication_policy 보다 낮은 우선순위를 가진다고 합니다.

authenication_policy 의 디폴트 값은 '*, ,' 이고,
공식문서상에선 아래와같이 열거형으로 사용하는듯 합니다.
authenication_policy = 'caching_sha2_password, sha256_password'

테스트결과 
`set global authentication_policy = 'mysql_native_password';`

설정 후 사용자를 만들어보니

플러그인 값이 mysql_native_password 로 설정되어있는것을 확인할 수 있었습니다. 
(첨부파일 [참조)](<img width="719" alt="스크린샷 2022-08-06 오전 3 21 13" src="https://user-images.githubusercontent.com/42140949/183139686-68cd10af-5138-4b6f-87f7-0fc1b0ecf2c3.png">)

공식문서에도 딱히 표기는 없었으나 아마 추측상 default_authentication_plugin는 오류메세지와 같이 read_only 속성을 가지고 있어 변경이 불가 한게 아닐까 싶습니다. 현재 mac 환경이라 my.cnf 조작이 수월하지 않아 my.cnf 에서수정하면 변경이 될지는 잘 모르겠는데 나중에 테스트 한번 해보겠습니다.

**Comment by haedoang** [comment]
오 확인해주셔서 감사합니다 🙇
